spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sunset_barbers?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update